// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as PortalService from "./portalservice.js";
export {
    PortalService
};

export {
    AppStatus,
    PortMode
} from "./models.js";

export type {
    AppInput,
    AppView,
    BackendSpec,
    CategoryEntry,
    EnvVar,
    GatewayStatus,
    LogEvent
} from "./models.js";
