// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppInput {
    "id": string | null;
    "name": string;
    "description": string;
    "hostname": string;
    "categoryId": string;
    "folder": string;
    "command": string;
    "portMode": PortMode;
    "port": number | null;
    "portEnv": string;
    "wakeOnRequest": boolean | null;
    "idleStopMin": number | null;
    "env": EnvVar[] | null;
    "backends": BackendSpec[] | null;
}

export enum AppStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AppStatusStopped = "stopped",
    AppStatusIdle = "idle",
    AppStatusStarting = "starting",
    AppStatusRunning = "running",
    AppStatusError = "error",
};

export interface AppView {
    "id": string;
    "name": string;
    "description": string;
    "hostname": string;
    "categoryId": string;
    "folder": string;
    "command": string;
    "portMode": PortMode;
    "port": number | null;
    "portEnv": string;
    "wakeOnRequest": boolean;
    "idleStopMin": number;
    "pinned": boolean;
    "idleUntil": number | null;
    "env": EnvVar[] | null;
    "backends": BackendSpec[] | null;
    "backendPids": number[] | null;
    "status": AppStatus;
    "url": string | null;
    "favicon": string | null;
    "pid": number | null;
    "error": string | null;
}

export interface BackendSpec {
    "name": string;
    "folder": string;
    "command": string;
    "portMode": PortMode;
    "port": number | null;
    "portEnv": string;
    "appPortEnv": string;
    "env": EnvVar[] | null;
}

export interface CategoryEntry {
    "id": string;
    "name": string;
    "color": string;
}

export interface EnvVar {
    "name": string;
    "value": string;
}

export interface GatewayStatus {
    "addr": string;
    "port": number;
    "preferredPort": number;
    "running": boolean;
    "error": string;
    "note": string;
}

export interface LogEvent {
    "id": string;
    "stream": string;
    "line": string;
}

export enum PortMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PortModeAuto = "auto",
    PortModeManual = "manual",
};
