// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteApp(id: string): $CancellablePromise<void> {
    return $Call.ByID(1334454351, id);
}

export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1089872012);
}

export function GetGatewayStatus(): $CancellablePromise<$models.GatewayStatus> {
    return $Call.ByID(1984671839);
}

export function GetLogs(id: string): $CancellablePromise<$models.LogEvent[] | null> {
    return $Call.ByID(3985295442, id);
}

export function ListApps(): $CancellablePromise<$models.AppView[] | null> {
    return $Call.ByID(2911868755);
}

export function OpenAppURL(raw: string): $CancellablePromise<void> {
    return $Call.ByID(1192352855, raw);
}

export function OpenConfigPath(): $CancellablePromise<void> {
    return $Call.ByID(1086019818);
}

export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(1305646314);
}

export function SetGatewayPort(port: number): $CancellablePromise<$models.GatewayStatus> {
    return $Call.ByID(930655546, port);
}

export function SetPinned(id: string, pinned: boolean): $CancellablePromise<$models.AppView> {
    return $Call.ByID(1478943487, id, pinned);
}

export function StartApp(id: string): $CancellablePromise<$models.AppView> {
    return $Call.ByID(1698769676, id);
}

export function StartGateway(): $CancellablePromise<$models.GatewayStatus> {
    return $Call.ByID(1431095513);
}

export function StopApp(id: string): $CancellablePromise<$models.AppView> {
    return $Call.ByID(156068370, id);
}

export function StopGateway(): $CancellablePromise<$models.GatewayStatus> {
    return $Call.ByID(1075979311);
}

export function UpsertApp(input: $models.AppInput): $CancellablePromise<$models.AppView> {
    return $Call.ByID(3170962151, input);
}
