// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../taiyop/devportal/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app-log": main$0.LogEvent;
            "app-status": main$0.AppView;
            "gateway-status": main$0.GatewayStatus;
        }
    }
}
